camerator/apps/blog/urls.py
from django.urls import path, re_path

from apps.blog import views

app_name = "blog"

urlpatterns = [
    path("list/", views.PostListView.as_view(), name="list-view"),
    re_path(
        r"(?P<slug>[-\w]+)/detail/", views.PostDetailView.as_view(), name="detail-view"
    ),
    re_path(
        r"(?P<slug>[-\w]+)/comment/form",
        views.CommentCreateView.as_view(),
        name="comment-form",
    ),
    re_path(
        r"(?P<pk>[-\w]+)/reply/form",
        views.CommentReplyCreateView.as_view(),
        name="comment-reply-form-view",
    ),
]

camerator/apps/website/urls.py
from django.urls import path

from apps.website import views

app_name = "website"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index-view"),
    path("contact/", views.ContactUsFormView.as_view(), name="contact-us-view"),
    path("about/", views.AboutView.as_view(), name="about-us-view"),
    path(
        "newsletter/form",
        views.NewsletterCreateView.as_view(),
        name="newsletter-form-view",
    ),
]

camerator/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import URLPattern, URLResolver, include, path, re_path
from django.views import defaults as default_views
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

TURLList = list[URLPattern | URLResolver]


schema_view = get_schema_view(
    openapi.Info(
        title="Camerator API",
        default_version="v1",
        description="Number one solution for photographers",
        contact=openapi.Contact(email="m.hassani.de@gmail.com"),
    ),
    public=False,
)

urlpatterns: TURLList = [
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path(settings.ADMIN_URL, admin.site.urls),
    # API base url
    path("api/", include("config.api_router")),
    path("blog/", include("apps.blog.urls")),
    path("", include("apps.website.urls")),
    path("services/", include("apps.service.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = urlpatterns + [path("__debug__/", include(debug_toolbar.urls))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

camerator/apps/website/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("created_date",)

    def __str__(self):
        return self.name


class Newsletter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

camerator/apps/website/forms.py
from django import forms

from .models import Contact, Newsletter


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"


class NewsletterForm(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = "__all__"

camerator/apps/website/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView
from django.views.generic.edit import FormView

from apps.blog.models import Post
from apps.website.models import Newsletter

from .forms import ContactForm, NewsletterForm


class IndexView(TemplateView):
    template_name = "website/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.objects.filter(
            status=Post.PostChoices.PUBLISHED
        ).order_by("-id")[0:9]
        return context


class AboutView(TemplateView):
    template_name = "website/about.html"


class ContactUsFormView(FormView):
    form_class = ContactForm
    template_name = "website/contact.html"

    success_url = reverse_lazy("website:contact-us-view")

    def form_valid(self, form):
        form.save()
        messages.success(
            self.request, "Your contact form has been submited successfully"
        )
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Your contact has not been submited successfully")
        return super().form_invalid(form)


class NewsletterCreateView(CreateView):
    model = Newsletter
    form_class = NewsletterForm
    template_name = "website/newsletter-form.html"
    success_url = "/"

    def fom_valid(self, form):
        form.save()
        messages.success(
            self.request, "Your newsletter has been submitted successfully"
        )
        return super().form_valid(form)

    def fom_invalid(self, form):
        messages.success(
            self.request, "Your newsletter has not been submitted successfully"
        )
        return super().form_valid(form)

camerator/templates/website/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="ftco-about img ftco-section ftco-no-pt ftco-no-pb" id="about-section">
	<div class="container-fluid px-0">
		<div class="row d-flex">
			<div class="col-md-6 d-flex">
				<div class="img d-flex align-self-stretch align-items-center js-fullheight" style="background-image:url({% static 'images/about.jpg' %});">
				</div>
			</div>
			<div class="col-md-6 d-flex align-items-center">
				<div class="text px-4 pt-5 pt-md-0 px-md-4 pr-md-5 ftco-animate">
					<h2 class="mb-4">Hello! I'm<span>Jeffrey White</span> the CEO of a Mostudio Photography</h2>
					<p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
					<div class="team-wrap row mt-4">
						<div class="col-md-4 team">
							<div class="img" style="background-image: url({% static 'images/team-1.jpg' %});"></div>
							<h3>John Doe</h3>
							<span>Photographer</span>
						</div>
						<div class="col-md-4 team">
							<div class="img" style="background-image: url({% static 'images/team-2.jpg' %});"></div>
							<h3>John Flex</h3>
							<span>Photographer</span>
						</div>
						<div class="col-md-4 team">
							<div class="img" style="background-image: url({% static 'images/team-3.jpg' %});"></div>
							<h3>John Flex</h3>
							<span>Photographer</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock content %}

camerator/templates/website/contact-form.html
{% load static %}

<div class="col-lg-8 col-md-7 order-md-last d-flex align-items-stretch">
    <div class="contact-wrap w-100 p-md-5 p-4">
        <h3 class="mb-4 heading">Get in touch</h3>
        <form method="POST" action="{% url 'website:contact-us-view' %}" id="contactForm" name="contactForm"
            class="contactForm">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="label" for="name">Full Name</label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="Name" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="label" for="email">Email Address</label>
                        <input type="email" class="form-control" name="email" id="email" placeholder="Email" required>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="label" for="subject">Subject</label>
                        <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject"
                            required>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="label" for="#">Message</label>
                        <textarea name="message" class="form-control" id="message" cols="30" rows="4"
                            placeholder="Message" required></textarea>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <input type="submit" value="Send Message" class="btn btn-primary">
                        <div class="submitting"></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

camerator/templates/website/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if messages %}
<ul class="messages">
	{% for message in messages %}
	<li {% if message.tags %} class="message {{ message.tags }}" {% endif %}>
		{{ message }}
		<span class="close-message">&times;</span>
	</li>
	{% endfor %}
</ul>
{% endif %}
<section class="ftco-section ftco-no-pt ftco-no-pb">
	<div class="container px-md-0">
		<div class="row d-flex no-gutters">
			{% include "website/contact-form.html" %}
			<div class="col-lg-4 col-md-5 d-flex align-items-stretch">
				<div class="info-wrap js-fullheight bg-primary w-100 p-md-5 p-4">
					<h3>Let's get in touch</h3>
					<p class="mb-4">We're open for any suggestion or just to have a chat</p>
					<div class="dbox w-100 d-flex align-items-start">
						<div class="icon d-flex align-items-center justify-content-center">
							<span class="fa fa-map-marker"></span>
						</div>
						<div class="text pl-3">
							<p><span>Address:</span> Rezvan 13th Street, Kerman Iran</p>
						</div>
					</div>
					<div class="dbox w-100 d-flex align-items-center">
						<div class="icon d-flex align-items-center justify-content-center">
							<span class="fa fa-phone"></span>
						</div>
						<div class="text pl-3">
							<p><span>Phone:</span> <a href="tel://1234567920">+ 98 939 373 1284</a></p>
						</div>
					</div>
					<div class="dbox w-100 d-flex align-items-center">
						<div class="icon d-flex align-items-center justify-content-center">
							<span class="fa fa-paper-plane"></span>
						</div>
						<div class="text pl-3">
							<p><span>Email:</span> <a href="mailto:info@yoursite.com">arshiasheikhbahayi@ygmail.com</a>
							</p>
						</div>
					</div>
					<div class="dbox w-100 d-flex align-items-center">
						<div class="icon d-flex align-items-center justify-content-center">
							<span class="fa fa-globe"></span>
						</div>
						<div class="text pl-3">
							<p><span>Website</span> <a href="#">Camerator</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="map row d-flex no-gutters">
			<div id="map"></div>
		</div>
	</div>
</section>
{% block extra_js %}
<script type="text/javascript">
	let center = [56.967999, 30.283937]
	const map = tt.map({
		key: "X9VqCRIgulmGAgPh2AiKnANfzPIVjYS9",
		container: "map",
		center: center,
		zoom: 10
	})
	map.on('load', () => {
		new tt.Marker().setLngLat(center).addTo(map)
	})
</script>

<style>
	.messages {
		position: fixed;
		top: 20px;
		right: 20px;
		z-index: 9999;
	}

	.message {
		padding: 10px 20px;
		margin-bottom: 10px;
		background-color: #f8f9fa;
		border-radius: 5px;
		opacity: 1;
		transition: opacity 1s ease-in-out;
	}

	.message.success {
		background-color: #d4edda;
		border: 1px solid #c3e6cb;
		color: #155724;
	}

	.message.error {
		background-color: #f8d7da;
		border: 1px solid #e3c9cc;
		color: #721c24;
	}

	.close-message {
		float: right;
		font-size: 20px;
		font-weight: bold;
		line-height: 1;
		color: #000;
		text-shadow: 0 1px 0 #fff;
		opacity: 0.5;
		cursor: pointer;
	}

	.close-message:hover {
		opacity: 0.8;
	}

	@keyframes fadeOut {
		0% {
			opacity: 1;
		}

		100% {
			opacity: 0;
		}
	}

	.message.fade-out {
		animation: fadeOut 1s ease-in-out forwards;
	}
</style>

<script>
	document.addEventListener("DOMContentLoaded", function () {
		const closeMessages = document.querySelectorAll(".close-message");
		closeMessages.forEach(function (closeMessage) {
			closeMessage.addEventListener("click", function () {
				const message = closeMessage.closest(".message");
				message.classList.add("fade-out");
				setTimeout(function () {
					message.remove();
				}, 1000);
			});
		});

		setTimeout(function () {
			const messages = document.querySelectorAll(".message");
			messages.forEach(function (message) {
				message.classList.add("fade-out");
				setTimeout(function () {
					message.remove();
				}, 1000);
			});
		}, 10000);
	});
</script>
{% endblock extra_js %}

{% endblock content %}

camerator/templates/website/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="ftco-section ftco-no-pt ftco-no-pb">
	<div class="container px-md-0">
		<div class="row d-flex no-gutters">
			{% for post in posts %}
			{%if post.id|divisibleby:2 %}
			<div class="col-md-12 portfolio-wrap">
				<div class="row no-gutters align-items-center">
					<a href="{{post.image.url}}"
						class="col-md-6 img image-popup js-fullheight d-flex align-items-center justify-content-center"
						style="background-image: url({{post.image.url}});">
						<div class="icon d-flex align-items-center justify-content-center">
							<span class="fa fa-expand"></span>
						</div>
					</a>
					<div class="col-md-6">
						<div class="text pt-5 pl-0 px-lg-5 pl-md-4 ftco-animate">
							<div class="px-4 px-lg-4">
								<div class="desc">
									<div class="top">
										<span class="subheading">
											{% for cat in post.category.all %}
											<a href="#" data-category-id="{{cat.id}}"
												class="tag-cloud-link">{{cat.title}}</a>
											{% if not forloop.last %}
											,
											{% endif %}
											{% endfor %}
										</span>
										<h2 class="mb-4"><a href="{% url 'blog:list-view' %}">{{post.title}}</a></h2>
									</div>
									<div class="absolute">
										<p>{{post.caption}}</p>
									</div>
									<p><a href="{% url 'blog:detail-view' slug=post.slug %}" class="custom-btn">View
											Portfolio</a></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% else %}
			<div class="col-md-12 portfolio-wrap">
				<div class="row no-gutters align-items-center">
					<a href="{{post.image.url}}"
						class="col-md-6 order-md-last img image-popup js-fullheight d-flex align-items-center justify-content-center"
						style="background-image: url({{post.image.url}});">
						<div class="icon d-flex align-items-center justify-content-center">
							<span class="fa fa-expand"></span>
						</div>
					</a>
					<div class="col-md-6">
						<div class="text pt-5 px-md-5 ftco-animate">
							<div class="px-4 px-lg-4">
								<div class="desc text-md-right">
									<div class="top">
										<span class="subheading">
											{% for cat in post.category.all %}
											<a href="#" data-category-id="{{cat.id}}"
												class="tag-cloud-link">{{cat.title}}</a>
											{% if not forloop.last %}
											,
											{% endif %}
											{% endfor %}
										</span>
										<h2 class="mb-4"><a href="{% url 'blog:list-view' %}">{{post.title}}</a></h2>
									</div>
									<div class="absolute">
										<p>{{post.caption}}</p>
									</div>
									<p><a href="{% url 'blog:detail-view' slug=post.slug %}" class="custom-btn">View
											Portfolio</a></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% endif %}
			{% endfor %}
		</div>
	</div>
</section>

{% block extra_js %}
<script>
	$(document).ready(function () {
		$(".tag-cloud-link").click(function (e) {
			e.preventDefault();
			let category_id = $(this).data("category-id");
			let current_url = new URL(window.location.href);
			current_url.searchParams.set("category", category_id);
			window.location.href = `{% url 'blog:list-view'%}?category=${category_id}`;
		});
	});
</script>
{% endblock extra_js %}

{% endblock content %}

camerator/templates/website/newsletter-form.html
{% load static %}

<div class="mb-4">
    <h3>Subscribe for newsletter</h3>
    <form action="{% url 'website:newsletter-form-view' %}" method="post" class="colorlib-subscribe-form">
        {% csrf_token %}
        <div class="form-group d-flex">
            <div class="icon"><span class="icon-paper-plane"></span></div>
            <input name="email" type="text" class="form-control" placeholder="Enter Email Address">
        </div>
    </form>
</div>