camerator/apps/blog/urls.py
from django.urls import path, re_path

from apps.blog import views

app_name = "blog"

urlpatterns = [
    path("list/", views.PostListView.as_view(), name="list-view"),
    re_path(
        r"(?P<slug>[-\w]+)/detail/", views.PostDetailView.as_view(), name="detail-view"
    ),
    re_path(
        r"(?P<slug>[-\w]+)/comment/form",
        views.CommentCreateView.as_view(),
        name="comment-form",
    ),
    re_path(
        r"(?P<pk>[-\w]+)/reply/form",
        views.CommentReplyCreateView.as_view(),
        name="comment-reply-form-view",
    ),
]

camerator/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import URLPattern, URLResolver, include, path, re_path
from django.views import defaults as default_views
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

TURLList = list[URLPattern | URLResolver]


schema_view = get_schema_view(
    openapi.Info(
        title="Camerator API",
        default_version="v1",
        description="Number one solution for photographers",
        contact=openapi.Contact(email="m.hassani.de@gmail.com"),
    ),
    public=False,
)

urlpatterns: TURLList = [
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path(settings.ADMIN_URL, admin.site.urls),
    # API base url
    path("api/", include("config.api_router")),
    path("blog/", include("apps.blog.urls")),
    path("", include("apps.website.urls")),
    path("services/", include("apps.service.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = urlpatterns + [path("__debug__/", include(debug_toolbar.urls))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

camerator/apps/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.timezone import now

User = get_user_model()


class PostCategory(models.Model):
    title = models.CharField(max_length=200, unique=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Gallery(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Post(models.Model):
    class PostChoices(models.TextChoices):
        PUBLISHED = "published"
        DRAFT = "draft"

    title = models.CharField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    gallery = models.ForeignKey(
        Gallery, related_name="images", on_delete=models.CASCADE, null=True
    )
    slug = models.SlugField(allow_unicode=True)
    image = models.ImageField(upload_to="posts/images/", blank=False, null=False)
    category = models.ManyToManyField(PostCategory, blank=False, related_name="posts")
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    publish_date = models.DateTimeField(default=now, blank=True, null=True)
    status = models.CharField(choices=PostChoices.choices, default="draft")
    caption = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-created_date"]
        app_label = "blog"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_date"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"


class CommentReply(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name="replies"
    )
    body = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

camerator/apps/blog/forms.py
from django import forms

from apps.blog.models import Comment, CommentReply


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "email", "body")


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = CommentReply
        fields = ("body",)

camerator/apps/blog/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView

from apps.blog.forms import CommentForm, CommentReplyForm
from apps.blog.models import Comment, Post, PostCategory


class PostListView(ListView):
    template_name = "blog/post-list.html"
    context_object_name = "posts"
    paginate_by = 9

    def get_queryset(self):
        queryset = Post.objects.filter(status=Post.PostChoices.PUBLISHED)
        if search_q := self.request.GET.get("q"):
            queryset = queryset.filter(title__icontains=search_q)
        if category_id := self.request.GET.get("category"):
            queryset = queryset.filter(category__id=category_id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = PostCategory.objects.all()
        return context


class PostDetailView(DetailView):
    model = Post
    slug_field = "slug"
    template_name = "blog/post-detail.html"
    context_object_name = "post"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comments"] = Comment.objects.filter(post=context["post"])
        return context


class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = "blog/comment-form.html"

    def form_valid(self, form):
        post = get_object_or_404(Post, slug=self.kwargs["slug"])
        form.instance.post = post
        messages.success(self.request, "Your commment has been submited successfully")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request, "Your comment couldn't be submitted. Please try again."
        )
        return super().form_invalid(form)

    def get_success_url(self):
        success_url = reverse("blog:detail-view", kwargs={"slug": self.kwargs["slug"]})
        return success_url


class CommentReplyCreateView(CreateView):
    model = CommentReplyForm
    form_class = CommentReplyForm
    template_name = "blog/comment-reply-form.html"

    def form_valid(self, form):
        comment = get_object_or_404(Comment, id=self.kwargs["pk"])
        form.instance.comment = comment
        messages.success(self.request, "Your reply has been submited successfully")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Your reply has not been submited successfully")
        return super().form_invalid(form)

    def get_success_url(self):
        comment = get_object_or_404(Comment, id=self.kwargs["pk"])
        post_slug = comment.post.slug
        success_url = reverse("blog:detail-view", kwargs={"slug": post_slug})
        return success_url

camerator/templates/blog/comment-form.html
{% load static %}

<div class="comment-form-wrap col-md-12 pt-5">
    <h3 class="mb-5">Leave a comment</h3>
    <form action="{% url 'blog:comment-form' slug=post.slug  %}" method="post" class="p-3 p-md-5">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="name">Name *</label>
                    <input type="text" class="form-control" id="name" name="name" required>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="email">Email *</label>
                    <input type="email" class="form-control" id="email" name="email" required>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea name="body" id="message" cols="20" rows="5" class="form-control" required></textarea>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                </div>
            </div>
        </div>
    </form>
</div>

camerator/templates/blog/comment-reply-form.html
{% load static %}

<nav>
    <div class="comment-reply-form" style="padding: 20px;">
        <form action="{% url 'blog:comment-reply-form-view' pk=comment.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="body">Message *</label>
                <input class="form-control" id="body" name="body" rows="3" required>
            </div>
            <button type="submit" class="btn btn-primary">Reply</button>
        </form>
    </div>
</nav>

camerator/templates/blog/post-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if messages %}
<ul class="messages">
	{% for message in messages %}
	<li {% if message.tags %} class="message {{ message.tags }}" {% endif %}>
		{{ message }}
		<span class="close-message">&times;</span>
	</li>
	{% endfor %}
</ul>
{% endif %}
<section class="ftco-section ftco-no-pt ftco-no-pb">
	<div class="container px-md-0">
		<div class="row d-flex no-gutters">
			<div class="col-lg-12 pb-5 single">
				<div class="row">
					<div class="img img-single w-100" style="background-image: url({{post.image.url}});"></div>
					<div class="px-5 mt-4">
						<h1 class="mb-3">{{post.title}}</h1>
						<p>{{post.caption}}</p>
						<div class="tag-widget post-tag-container mb-5 mt-5">
							<div class="tagcloud">
								{% for cat in post.category.all %}
								<a href="#" data-category-id="{{cat.id}}" class="tag-cloud-link">{{cat.title}}</a>
								{% endfor %}
							</div>
						</div>

						<div class="about-author d-flex p-4">
							<div class="bio mr-5">
								<img src="{{post.author.image.url}}" alt="Image placeholder" class="img-fluid mb-4">
							</div>
							<div class="desc">
								<h3>{{post.author.first_name}} {{post.author.last_name}}</h3>
								<p>{{post.author.description}}</p>
							</div>
						</div>
						<div class="pt-5 mt-5">
							<h3 class="mb-5 font-weight-bold">6 Comments</h3>
							<ul class="comment-list">
								{% for comment in comments %}
								<li class="comment">
									<div class="vcard bio">
										<img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder">
									</div>
									<div class="comment-body">
										<h3>{{comment.name}}</h3>
										<div class="meta">{{comment.created_date}}</div>
										<p>{{comment.body}}</p>
									</div>
								</li>
								{% for reply in comment.replies.all %}
								<div class="comment-reply">
									<div class="comment-body">
										<p style="color: white;">-- {{reply.body}} --</p>
									</div>
								</div>
								{% endfor %}

								{% include "blog/comment-reply-form.html" %}

								{% endfor %}
							</ul>
							<!-- END comment-list -->


							{% include "blog/comment-form.html" %}
						</div>
					</div>
				</div><!-- END-->
			</div>
		</div>
	</div>
</section>

{% block extra_js %}
<script>
	$(document).ready(function () {
		let current_url_params = new URLSearchParams(window.location.search)
		$("#search-query-filter").val(current_url_params.get("q") || "")
		$("#category-id-filter").val(current_url_params.get("category_id") || "")

		$(".tag-cloud-link").click(function (e) {
			e.preventDefault();
			let category_id = $(this).data("category-id");
			let current_url = new URL(window.location.href);
			current_url.searchParams.set("category", category_id);
			window.location.href = `{% url 'blog:list-view'%}?category=${category_id}`;
		});
	});
</script>

<style>
	.messages {
		position: fixed;
		top: 20px;
		right: 20px;
		z-index: 9999;
	}

	.message {
		padding: 10px 20px;
		margin-bottom: 10px;
		background-color: #f8f9fa;
		border-radius: 5px;
		opacity: 1;
		transition: opacity 1s ease-in-out;
	}

	.message.success {
		background-color: #d4edda;
		border: 1px solid #c3e6cb;
		color: #155724;
	}

	.message.error {
		background-color: #f8d7da;
		border: 1px solid #e3c9cc;
		color: #721c24;
	}

	.close-message {
		float: right;
		font-size: 20px;
		font-weight: bold;
		line-height: 1;
		color: #000;
		text-shadow: 0 1px 0 #fff;
		opacity: 0.5;
		cursor: pointer;
	}

	.close-message:hover {
		opacity: 0.8;
	}

	@keyframes fadeOut {
		0% {
			opacity: 1;
		}

		100% {
			opacity: 0;
		}
	}

	.message.fade-out {
		animation: fadeOut 1s ease-in-out forwards;
	}
</style>

<script>
	document.addEventListener("DOMContentLoaded", function () {
		const closeMessages = document.querySelectorAll(".close-message");
		closeMessages.forEach(function (closeMessage) {
			closeMessage.addEventListener("click", function () {
				const message = closeMessage.closest(".message");
				message.classList.add("fade-out");
				setTimeout(function () {
					message.remove();
				}, 1000);
			});
		});

		setTimeout(function () {
			const messages = document.querySelectorAll(".message");
			messages.forEach(function (message) {
				message.classList.add("fade-out");
				setTimeout(function () {
					message.remove();
				}, 1000);
			});
		}, 10000);
	});
</script>
{% endblock extra_js %}

{% endblock content %}

camerator/templates/blog/post-list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="ftco-section ftco-no-pt ftco-no-pb">
	<div class="container px-md-0">
		<div class="row d-flex no-gutters">
			{% for post in posts %}
			<div class="col-md-4 portfolio-wrap-2">
				<div class="row no-gutters align-items-center">
					<div href="#" class="img w-100 js-fullheight d-flex align-items-center"
						style="background-image: url({{post.image.url}});">
						<div class="text p-4 p-md-5 ftco-animate">
							<div class="desc">
								<div class="top">
									<span class="subheading">{% for cat in post.category.all %} <a href="#"
											data-category-id="{{cat.id}}">{{cat.title}}</a> {% if not forloop.last %},
										{% endif %} {%endfor%}</span>
									<h2 class="mb-4"><a href="single.html">{{post.title}}</a></h2>
									<p><a href="{% url 'blog:detail-view' slug=post.slug %}" class="custom-btn">View
											Portfolio</a></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</section>

<div class="row pt-5 mt-3 pagination-container ">
	{% if page_obj.has_other_pages %}
	<!-- Pagination -->
	<nav aria-label="Page navigation">
		<ul class="pagination justify-content-center">
			{% if page_obj.has_previous %}
			<li class="page-item">
				<button class="page-link prev-button" onclick="changePage(`{{ page_obj.previous_page_number }}`)"
					aria-label="Previous">
					<span aria-hidden="true">
						<i class="bi-chevron-double-right small">Prev page</i>
					</span>
				</button>
			</li>
			{% endif %}
			{{page_obj.page_range}}
			{% for i in page_obj.paginator.page_range %}
			{% if page_obj.number == i %}
			<li><button class=" pagination-button">{{ i }}</li></button>
			{% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %} <li>
				<button class="pagination-button" onclick="changePage(`{{i}}`)">{{ i }}</button></li>
				{% endif %}
				{% endfor %}
				{% if page_obj.has_next %}
				<li class="page-item">
					<button class="page-link next-button " onclick="changePage(`{{ page_obj.next_page_number }}`)"
						aria-label="Previous">
						<span aria-hidden="true">
							<i class="bi-chevron-double-left small">Next page</i>
						</span>
					</button>
				</li>
				{% endif %}

		</ul>
	</nav>
	{% endif %}
	<!-- End Pagination -->
</div>
<!-- End Pagination -->
<style>
	.pagination-button {
		background-color: gold;
		margin: 2px;
		padding: 0.5rem 1rem;
		transition: background-color 0.3s ease;
	}

	.pagination-button:hover {
		transform: scale(1.2);
	}

	.pagination-button.active {
		background-color: rgb(237, 229, 186);
		padding: 0.5rem 1rem;
		transition: background-color 0.3s ease;
	}

	.next-button {
		background: gold;
		padding-bottom: 16px;
		margin: 2px;
	}

	.prev-button {
		background: gold;
		padding-bottom: 16px;
		margin: 2px;
	}

	.pagination-container {
		display: flex;
		justify-content: center;
		align-items: center;
		width: 100%;
		margin-top: 2rem;

	}
</style>

{% block extra_js %}
<script>
	$(document).ready(function () {
		let current_url_params = new URLSearchParams(window.location.search)
		$("#search-query-filter").val(current_url_params.get("q") || "")
		$("#category-id-filter").val(current_url_params.get("category_id") || "")

		$(".subheading a").click(function (e) {
			e.preventDefault();
			let category_id = $(this).data("category-id");
			let current_url = new URL(window.location.href);
			current_url.searchParams.set("category", category_id);
			window.location.href = current_url.href;
		});
	});
</script>
{% endblock extra_js %}

{% endblock content %}